# Generated by Django 2.2.1 on 2019-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190719_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salt',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
