# Generated by Django 2.2.1 on 2019-07-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='iv',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
