# Generated by Django 2.2.1 on 2019-07-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_friendship_accepted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
