# Generated by Django 2.2.1 on 2019-09-27 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190729_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
