# Generated by Django 2.2.1 on 2019-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_invite_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invite_code',
            field=models.UUIDField(),
        ),
    ]
