# Generated by Django 2.2.1 on 2019-11-11 13:14

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.FileField(default='none', upload_to='')),
                ('thumbnail', models.FileField(default='none', upload_to='')),
                ('cipher_object', jsonfield.fields.JSONField(default='none')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with', to='users.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='vlogs.Vlog')),
            ],
        ),
    ]
