# Generated by Django 2.2.1 on 2019-07-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vlog',
        ),
    ]
