# Generated by Django 2.2.1 on 2019-07-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0003_vlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='title',
        ),
        migrations.AddField(
            model_name='vlog',
            name='thumbnail',
            field=models.ImageField(default='https://i0.wp.com/www.quitealooker.com/wp-content/plugins/penci-portfolio//images/no-thumbnail.jpg?w=1170', upload_to=''),
        ),
    ]
