# Generated by Django 2.2.1 on 2019-07-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0004_auto_20190724_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
