# Generated by Django 2.2.1 on 2019-07-25 19:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0005_auto_20190725_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='cipher_object',
            field=jsonfield.fields.JSONField(),
        ),
    ]
