# Generated by Django 2.2.1 on 2019-09-01 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0006_auto_20190725_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
