# Generated by Django 2.2.1 on 2019-09-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0007_vlog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
