# Generated by Django 2.2.1 on 2019-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0008_dummytimestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
