# Generated by Django 2.2.1 on 2019-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0009_auto_20190901_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='timestamp',
            field=models.CharField(default='null', max_length=25),
        ),
    ]
