# Generated by Django 2.2.1 on 2019-09-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0010_auto_20190901_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='timestamp',
            field=models.CharField(max_length=25),
        ),
    ]
