# Generated by Django 2.2.1 on 2019-09-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0012_auto_20190901_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyTimeStamp',
        ),
    ]
