# Generated by Django 2.2.1 on 2019-09-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0013_delete_dummytimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vlog',
            old_name='file',
            new_name='playlist',
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='vlogs.Vlog')),
            ],
        ),
    ]
