# Generated by Django 2.2.1 on 2019-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0014_auto_20190923_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
