# Generated by Django 2.2.1 on 2019-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0015_auto_20190923_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='playlist',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.CharField(max_length=255),
        ),
    ]
