# Generated by Django 2.2.1 on 2019-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0016_auto_20190923_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='playlist',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
