# Generated by Django 2.2.1 on 2019-09-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0017_auto_20190923_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='timestamp',
        ),
    ]
