# Generated by Django 2.2.1 on 2019-10-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_profile_picture'),
        ('vlogs', '0018_remove_vlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlog',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_with', to='users.UserProfile'),
        ),
    ]
