# Generated by Django 2.2.1 on 2019-10-30 14:20

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0020_auto_20191030_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='cipher_object',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='playlist',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
