# Generated by Django 2.2.1 on 2019-10-31 09:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0021_auto_20191030_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='cipher_object',
            field=jsonfield.fields.JSONField(default='none'),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='playlist',
            field=models.FileField(default='none', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='thumbnail',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
