# Generated by Django 2.2.1 on 2019-10-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_profile_picture'),
        ('vlogs', '0022_auto_20191031_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestVlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_with_test', to='users.UserProfile')),
            ],
        ),
    ]
