# Generated by Django 2.2.1 on 2019-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0023_testvlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvlog',
            name='blah',
            field=models.CharField(default='blag', max_length=255),
        ),
    ]
