# Generated by Django 2.2.1 on 2019-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0024_testvlog_blah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvlog',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_with_test', to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='vlog',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared_with', to='users.UserProfile'),
        ),
    ]
