# Generated by Django 2.2.1 on 2019-10-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0025_auto_20191031_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestVlog',
        ),
    ]
