# Generated by Django 2.2.1 on 2019-11-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0026_delete_testvlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to='users.UserProfile'),
        ),
    ]
